<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <RootNamespace>AngryMonkey.CloudCommerce.Demo</RootNamespace>
    <UserSecretsId>AngryMonkey.CloudCommerce.Demo</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CloudCommerce\CloudCommerce.csproj" />
    <ProjectReference Include="..\CloudCommerce.Components\CloudCommerce.Components.csproj" />
    <ProjectReference Include="..\CloudPayments.Stripe\CloudPayments.Stripe.csproj" />
    <ProjectReference Include="..\CloudPayments.PayPal\CloudPayments.PayPal.csproj" />
    <ProjectReference Include="..\CloudPayments.Adyen\CloudPayments.Adyen.csproj" />
    <ProjectReference Include="..\CloudPayments.MyFatoorah\CloudPayments.MyFatoorah.csproj" />
    <ProjectReference Include="..\CloudPayments.SkipCash\CloudPayments.SkipCash.csproj" />
    <ProjectReference Include="..\CloudPayments.Tap\CloudPayments.Tap.csproj" />
    <ProjectReference Include="..\CloudPayments.PayTabs\CloudPayments.PayTabs.csproj" />
    <ProjectReference Include="..\CloudLogistics.Aramex\CloudLogistics.Aramex.csproj" />
    <ProjectReference Include="..\CloudLogistics.DhlExpress\CloudLogistics.DhlExpress.csproj" />
    <ProjectReference Include="..\CloudLogistics.FedEx\CloudLogistics.FedEx.csproj" />
  </ItemGroup>
</Project>
